# Generated by Django 4.1.8 on 2023-04-22 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagementSystemApp', '0002_alter_project_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 20, 59, 30, 191018)),
        ),
    ]
